# Site settings
title:  Learning Haskell
header-img: img/header.jpg
email: eva.villarroya@gmail.com
description: "Learning Haskell for fun"
baseurl: 
url: "http://eva-villarroya.github.io"
twitter_username: evillarroya
github_username:  eva-villarroya
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
